version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8083:8083"
      - "8084:8084"
    container_name: ${PROJECT_NAME}-nginx
    depends_on:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"
  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./laravel/:/var/www/laravel
    working_dir: /var/www/laravel
    container_name: ${PROJECT_NAME}-laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: docker_db
    ports:
      - "5433:5433"
    volumes:
      - ./docker/db:/var/lib/postgresql/data

  phppgadmin:
    container_name: ${PROJECT_NAME}-phppgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 1111
